### ISSUE TITLE
Err 500 module 'jinja2' has no attribute 'Markup'

### ISSUE THREAD

**Issue by pax** [simonw/datasette-mask-columns#3]
At first attempt of masking columns, I get `module 'jinja2' has no attribute 'Markup'`

![Screenshot 2023-01-24 at 18 33 44](https://user-images.githubusercontent.com/116795/214352088-7015036d-828a-4fa6-9b5e-10f01d9443b6.png)

![Screenshot 2023-01-24 at 18 33 30](https://user-images.githubusercontent.com/116795/214352069-5d922a28-76d7-4765-a278-d2cf757d5f27.png)

**Comment by garthk** [comment]
Confirmed with any:
```plain
datasette-mask-columns == 0.2.1
Jinja2 >= 3.1.0
```

**Comment by garthk** [comment]
Better yet, see pallets/jinja#1544.
